name: Deploy React App to S3

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Download build artifact
              uses: actions/download-artifact@v2
              with:
                  name: react-build

            - name: Sync build to S3
              run: |
                  aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
